-- AlphaFest HF52.1 — métricas privadas do site
-- Execute UMA vez no SQL Editor do Supabase.

create table if not exists public.site_metrics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view','product_open','whatsapp_click')),
  product_name text not null default '',
  page_path text not null default '',
  referrer text not null default '',
  client_id text not null default '',
  session_id text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists site_metrics_events_type_created_idx
  on public.site_metrics_events (event_type, created_at desc);
create index if not exists site_metrics_events_product_created_idx
  on public.site_metrics_events (product_name, created_at desc);

alter table public.site_metrics_events enable row level security;

grant insert on table public.site_metrics_events to anon, authenticated;
grant usage, select on sequence public.site_metrics_events_id_seq to anon, authenticated;
revoke select, update, delete on table public.site_metrics_events from anon, authenticated;

drop policy if exists "public_insert_site_metrics" on public.site_metrics_events;
create policy "public_insert_site_metrics"
  on public.site_metrics_events
  for insert
  to anon, authenticated
  with check (
    event_type in ('page_view','product_open','whatsapp_click')
    and length(product_name) <= 180
    and length(page_path) <= 300
    and length(referrer) <= 500
    and length(client_id) <= 100
    and length(session_id) <= 100
  );

-- O Manager usa SUPABASE_SERVICE_KEY e, portanto, lê os dados no servidor.
-- Nenhuma política SELECT é criada para visitantes do site.
